---
database:
    host:
    port: 5432
    dbname: osm
    user: osm
    password: osm
    publication: osm_publication
    replication_slot: osm_repl
log_dir: /tmp
changes_dir: /tmp
tmp_dir: /tmp
run_dir: /tmp
