name: Install Prerequisites

runs:
  using: composite

  steps:
    - name: Install packages
      run: |
        apt-get update -qq
        apt-get install -yq --no-install-suggests \
            clang \
            clang-tidy \
            cmake \
            g++ \
            gettext-base \
            git \
            gnupg \
            libboost-program-options-dev \
            libbz2-dev \
            libexpat1-dev \
            libpqxx-dev \
            libyaml-cpp-dev \
            make \
            pandoc \
            postgresql-common \
            zlib1g-dev
      shell: bash

    - name: Install libosmium from git
      run: |
        git clone --quiet --depth 1 https://github.com/osmcode/libosmium.git ../libosmium
      shell: bash
