name: CMake

runs:
    using: composite
    steps:
      - name: Create build directory
        run: mkdir build
        shell: bash
      - name: Configure
        run: |
          cmake -LA -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
                -DPG_CONFIG=/usr/lib/postgresql/${PG_VERSION}/bin/pg_config \
                -DPG_VIRTUALENV_VERSION=-v${PG_VERSION} \
                -DOSMIUM_INCLUDE_DIR=../../libosmium/include \
                ..
        shell: bash
        working-directory: build
