name: CI

on: [ push, pull_request ]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - "ubuntu:22.04"    # gcc 11.2.0, clang 14.0.0, cmake 3.22.1, pg14
          - "ubuntu:24.04"    # gcc 13.2.0, clang 18.0.0, cmake 3.28.3, pg16
          - "debian:bookworm" # gcc 10.2.1, clang 11.0.1, cmake 3.18.4, pg13
          - "debian:trixie"   # gcc 13.2.0, clang 16.0.0, cmake 3.29.2, pg16
        build_type: [Debug]
        cpp_compiler: [g++]
        install_pg_apt_repo: [no]
        include:
          - image: "ubuntu:22.04"
            pg_version: 14
          - image: "ubuntu:24.04"
            pg_version: 16
          - image: "debian:bookworm"
            pg_version: 13
            install_pg_apt_repo: yes
          - image: "debian:bookworm"
            pg_version: 15
          - image: "debian:bookworm"
            pg_version: 15
            c_compiler: clang
            cpp_compiler: clang++
          - image: "debian:bookworm"
            pg_version: 15
            c_compiler: clang
            cpp_compiler: clang++
          - image: "debian:bookworm"
            pg_version: 15
            build_type: RelWithDebInfo
          - image: "debian:bookworm"
            pg_version: 15
            c_compiler: clang
            cpp_compiler: clang++
          - image: "debian:trixie"
            pg_version: 17
          - image: "debian:trixie"
            pg_version: 17
            c_compiler: clang
            cpp_compiler: clang++
    container:
      image: ${{ matrix.image }}
      env:
        BUILD_TYPE: ${{ matrix.build_type }}
        CC: ${{ matrix.c_compiler }}
        CXX: ${{ matrix.cpp_compiler }}
        CXXFLAGS: -Wall -pedantic -Wextra -Werror -Wno-error=deprecated-declarations
        APT_LISTCHANGES_FRONTEND: none
        DEBIAN_FRONTEND: noninteractive
        PG_VERSION: ${{ matrix.pg_version }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install
      - name: Optionally activate PostgreSQL APT repo
        if: matrix.install_pg_apt_repo == 'yes'
        shell: bash
        run: |
          echo | /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
      - uses: ./.github/actions/install-pg
      - uses: ./.github/actions/cmake
      - uses: ./.github/actions/build
      - uses: ./.github/actions/ctest

