name: clang-tidy

on: [ push, pull_request ]

jobs:
  linux:
    runs-on: ubuntu-latest
    container:
      image: "debian:testing"
      env:
        BUILD_TYPE: Debug
        CC: clang-19
        CXX: clang++-19
        CXXFLAGS: -Wall -pedantic -Wextra -Werror -Wno-error=deprecated-declarations
        APT_LISTCHANGES_FRONTEND: none
        DEBIAN_FRONTEND: noninteractive
        PG_VERSION: 17
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install
      - uses: ./.github/actions/install-pg
      - uses: ./.github/actions/cmake
      - uses: ./.github/actions/build
      - name: Run clang-tidy
        shell: bash
        run: make clang-tidy
        working-directory: build

